name: Symfony

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Install Dependencies
        run: composer install
      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run

  phpstan: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Install Dependencies
        run: composer install
      - name: Run PHP Stan
        run: vendor/bin/phpstan analyse
